"""Backward-compatible re-export of audio/Whisper settings.

Single source of truth is config.settings (env-overridable).
This module only re-exports so existing imports keep working.
"""

from config.settings import (
    WHISPER_MODEL_SIZE,
    WHISPER_LANGUAGE,
    WHISPER_BEAM_SIZE,
    WHISPER_BEST_OF,
    WHISPER_TEMPERATURE,
    DEBUG_TRANSCRIPTION,
    AUDIO_SAMPLE_RATE,
    AUDIO_CHANNELS,
    AUDIO_DTYPE,
    CHUNK_SIZE,
    PRE_SPEECH_BUFFER_SIZE,
    MIN_ACTIVATION_FRAMES,
    MAX_SILENCE_DURATION,
    MAX_RECORDING_SECONDS,
    MIN_SPEECH_DURATION,
    BASE_ENERGY_THRESHOLD,
    DYNAMIC_ENERGY_RATIO,
    NOISE_FLOOR_ALPHA,
    DEBUG_VAD,
)

__all__ = [
    "WHISPER_MODEL_SIZE",
    "WHISPER_LANGUAGE",
    "WHISPER_BEAM_SIZE",
    "WHISPER_BEST_OF",
    "WHISPER_TEMPERATURE",
    "DEBUG_TRANSCRIPTION",
    "AUDIO_SAMPLE_RATE",
    "AUDIO_CHANNELS",
    "AUDIO_DTYPE",
    "CHUNK_SIZE",
    "PRE_SPEECH_BUFFER_SIZE",
    "MIN_ACTIVATION_FRAMES",
    "MAX_SILENCE_DURATION",
    "MAX_RECORDING_SECONDS",
    "MIN_SPEECH_DURATION",
    "BASE_ENERGY_THRESHOLD",
    "DYNAMIC_ENERGY_RATIO",
    "NOISE_FLOOR_ALPHA",
    "DEBUG_VAD",
]
